### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by radiantone** [skarif2/node-rest-starter#6]
|master ✓| → npm start

> node-rest-starter@0.6.0 start xxxxx
> node ./src/index.js

xxxx/api/src/config/mongoose.js:34
  throw new Error(`Unable to connect to database: ${mongoUri}`)
  ^

Error: Unable to connect to database: localhost
    at NativeConnection.<anonymous> (xxx/api/src/config/mongoose.js:34:9)
    at NativeConnection.emit (events.js:314:20)
    at xxxx/api/node_modules/mongoose/lib/connection.js:809:37
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by alexbaker2002** [comment]
following the instructions, you should have copied the .env file which will contain the settings for your database. You have to replace the string with your connection string in order to get mongoose to connect.
